version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - amazon-linux-extras install docker -y
      - service docker start
      - usermod -a -G docker $USER
      - chmod 666 /var/run/do
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Running npm test in the Docker container...
      - docker run --rm $REPOSITORY_URI:$IMAGE_TAG npm test
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  discard-paths: yes