version: 0.2

phases:
  install:
    commands:
      - echo Increasing the limit of open file descriptors...
      - ulimit -n 4096
      - echo Installing npm dependencies...
      - npm instal
  build:
    commands:
      - npm test
reports:
  test-report:
    files:
      - '**/test-results.xml'
    discard-paths: no